version: '3.8'

volumes:
  eeg_data:
    driver: local
  eeg_models:
    driver: local

services:
  bci-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eeg-bci-processor
    volumes:
      - ./data:/app/data
      - eeg_models:/app/models
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eeg-jupyter
    volumes:
      - eeg_data:/app/data
      - eeg_models:/app/models
      - ./app:/app/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    profiles:
      - dev
